site_name: Gluetun Wiki
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tracking

  # logo: https://raw.githubusercontent.com/qdm12/gluetun/master/title.svg
# extra:
#   homepage: https://github.com/qdm12/gluetun

plugins:
  - tags
  - search
  - awesome-nav

repo_url: https://github.com/qdm12/gluetun

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
